apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2021-05-05T13:56:23Z"
  generation: 6
  labels:
    app: iam-php
    app.kubernetes.io/component: iam-php
    app.kubernetes.io/instance: iam-php
    app.kubernetes.io/part-of: iam-php
    app.openshift.io/runtime-namespace: djpconnect
    manager: openshift-controller-manager
    operation: Update
  name: iam-php
  namespace: djpconnect
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: iam-php
    deploymentconfig: iam-php
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: iam-php
        deploymentconfig: iam-php
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgresql://iam:iam@iam-db:5432/iam?serverVersion=11
        - name: MERCURE_PUBLISH_URL
          value: http://iam-caddy/.well-known/mercure
        - name: REDIS_URL
          value: iam-redis
        image: quay.io/fauzislami/iam-php:UPDATE
        imagePullPolicy: Always
        name: iam-php
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /srv/app/var
          name: iam-php-1
        - mountPath: /var/run/php
          name: iam-php-2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: djpconnect
      serviceAccountName: djpconnect
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: iam-php-1
      - emptyDir: {}
        name: iam-php-2
  test: false
  triggers:
  - type: ConfigChange
