version: '3'

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: iam_db_dev
      POSTGRES_PASSWORD: iam_db_dev
      POSTGRES_DB: iam_db_dev
    ports: [5432]

  redis:
    image: redis:latest
    ports: [6379]
