<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210628045326 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE refresh_tokens_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE aplikasi (id UUID NOT NULL, nama VARCHAR(255) NOT NULL, system_name VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, create_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deskripsi TEXT DEFAULT NULL, host_name VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_aplikasi_nama_status ON aplikasi (nama, system_name, status)');
        $this->addSql('CREATE INDEX idx_aplikasi_url ON aplikasi (id, nama, host_name, url)');
        $this->addSql('COMMENT ON COLUMN aplikasi.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN aplikasi.create_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE eselon (id UUID NOT NULL, nama VARCHAR(255) NOT NULL, tingkat INT NOT NULL, kode VARCHAR(255) NOT NULL, legacy_kode INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_eselon_nama_status ON eselon (id, nama, tingkat)');
        $this->addSql('CREATE INDEX idx_eselon_legacy ON eselon (id, legacy_kode)');
        $this->addSql('COMMENT ON COLUMN eselon.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE "group" (id UUID NOT NULL, owner_id UUID NOT NULL, nama VARCHAR(255) NOT NULL, system_name VARCHAR(255) NOT NULL, deskripsi TEXT DEFAULT NULL, create_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6DC044C57E3C61F9 ON "group" (owner_id)');
        $this->addSql('CREATE INDEX idx_group_data ON "group" (id, nama, system_name, status)');
        $this->addSql('CREATE INDEX idx_group_relation ON "group" (id, owner_id)');
        $this->addSql('COMMENT ON COLUMN "group".id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "group".owner_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "group".create_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE group_jabatan (id UUID NOT NULL, nama VARCHAR(255) NOT NULL, legacy_kode VARCHAR(4) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_group_jabatan_nama ON group_jabatan (id, nama)');
        $this->addSql('CREATE INDEX idx_group_jabatan_legacy ON group_jabatan (id, legacy_kode)');
        $this->addSql('COMMENT ON COLUMN group_jabatan.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE group_member (id UUID NOT NULL, group_id_id UUID NOT NULL, user_id UUID NOT NULL, join_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A36222A82F68B530 ON group_member (group_id_id)');
        $this->addSql('CREATE INDEX IDX_A36222A8A76ED395 ON group_member (user_id)');
        $this->addSql('CREATE INDEX idx_group_member_data ON group_member (id, status, user_id)');
        $this->addSql('CREATE INDEX idx_group_member_relation ON group_member (id, group_id_id, user_id)');
        $this->addSql('COMMENT ON COLUMN group_member.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN group_member.group_id_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN group_member.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN group_member.join_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE jabatan (id UUID NOT NULL, eselon_id UUID DEFAULT NULL, group_jabatan_id UUID DEFAULT NULL, nama VARCHAR(255) NOT NULL, level INT NOT NULL, jenis VARCHAR(255) NOT NULL, tanggal_aktif TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tanggal_nonaktif TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sk VARCHAR(255) DEFAULT NULL, legacy_kode VARCHAR(4) DEFAULT NULL, legacy_kode_jab_keu VARCHAR(4) DEFAULT NULL, legacy_kode_grade_keu VARCHAR(4) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_947E72542D0196DB ON jabatan (eselon_id)');
        $this->addSql('CREATE INDEX IDX_947E7254708D6535 ON jabatan (group_jabatan_id)');
        $this->addSql('CREATE INDEX idx_jabatan_nama_status ON jabatan (id, nama, level, jenis)');
        $this->addSql('CREATE INDEX idx_jabatan_legacy ON jabatan (id, legacy_kode)');
        $this->addSql('CREATE INDEX idx_jabatan_relation ON jabatan (id, eselon_id)');
        $this->addSql('COMMENT ON COLUMN jabatan.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN jabatan.eselon_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN jabatan.group_jabatan_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN jabatan.tanggal_aktif IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN jabatan.tanggal_nonaktif IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE jabatan_unit (jabatan_id UUID NOT NULL, unit_id UUID NOT NULL, PRIMARY KEY(jabatan_id, unit_id))');
        $this->addSql('CREATE INDEX IDX_C6797710A7400487 ON jabatan_unit (jabatan_id)');
        $this->addSql('CREATE INDEX IDX_C6797710F8BD700D ON jabatan_unit (unit_id)');
        $this->addSql('COMMENT ON COLUMN jabatan_unit.jabatan_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN jabatan_unit.unit_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE jabatan_atribut (id UUID NOT NULL, nama VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_jabatan_atribut_nama ON jabatan_atribut (id, nama)');
        $this->addSql('COMMENT ON COLUMN jabatan_atribut.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE jabatan_pegawai (id UUID NOT NULL, pegawai_id UUID NOT NULL, jabatan_id UUID NOT NULL, tipe_id UUID DEFAULT NULL, kantor_id UUID NOT NULL, unit_id UUID DEFAULT NULL, atribut_id UUID DEFAULT NULL, referensi VARCHAR(255) DEFAULT NULL, tanggal_mulai TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tanggal_selesai TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_53FE676A998300D9 ON jabatan_pegawai (pegawai_id)');
        $this->addSql('CREATE INDEX IDX_53FE676AA7400487 ON jabatan_pegawai (jabatan_id)');
        $this->addSql('CREATE INDEX IDX_53FE676AC69A8E08 ON jabatan_pegawai (tipe_id)');
        $this->addSql('CREATE INDEX IDX_53FE676A2C104734 ON jabatan_pegawai (kantor_id)');
        $this->addSql('CREATE INDEX IDX_53FE676AF8BD700D ON jabatan_pegawai (unit_id)');
        $this->addSql('CREATE INDEX IDX_53FE676A89E8E03D ON jabatan_pegawai (atribut_id)');
        $this->addSql('CREATE INDEX idx_jabatan_pegawai ON jabatan_pegawai (id, tanggal_mulai, tanggal_selesai)');
        $this->addSql('CREATE INDEX idx_jabatan_pegawai_relation ON jabatan_pegawai (id, pegawai_id, jabatan_id, tipe_id, kantor_id, unit_id)');
        $this->addSql('COMMENT ON COLUMN jabatan_pegawai.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN jabatan_pegawai.pegawai_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN jabatan_pegawai.jabatan_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN jabatan_pegawai.tipe_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN jabatan_pegawai.kantor_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN jabatan_pegawai.unit_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN jabatan_pegawai.atribut_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN jabatan_pegawai.tanggal_mulai IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN jabatan_pegawai.tanggal_selesai IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE jenis_kantor (id UUID NOT NULL, nama VARCHAR(255) NOT NULL, tipe VARCHAR(255) NOT NULL, klasifikasi INT NOT NULL, tanggal_aktif TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tanggal_nonaktif TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, legacy_id INT DEFAULT NULL, legacy_kode INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_jenis_kantor_nama_status ON jenis_kantor (id, nama, tipe, klasifikasi)');
        $this->addSql('CREATE INDEX idx_jenis_kantor_legacy ON jenis_kantor (id, legacy_kode, legacy_id)');
        $this->addSql('COMMENT ON COLUMN jenis_kantor.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN jenis_kantor.tanggal_aktif IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN jenis_kantor.tanggal_nonaktif IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE kantor (id UUID NOT NULL, jenis_kantor_id UUID NOT NULL, parent_id UUID DEFAULT NULL, pembina_id UUID DEFAULT NULL, nama VARCHAR(255) NOT NULL, level INT DEFAULT NULL, tanggal_aktif TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tanggal_nonaktif TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sk VARCHAR(255) DEFAULT NULL, alamat TEXT DEFAULT NULL, telp VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, zona_waktu VARCHAR(4) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, legacy_kode VARCHAR(10) DEFAULT NULL, legacy_kode_kpp VARCHAR(3) DEFAULT NULL, legacy_kode_kanwil VARCHAR(3) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A3CC27035EB4E08C ON kantor (jenis_kantor_id)');
        $this->addSql('CREATE INDEX IDX_A3CC2703727ACA70 ON kantor (parent_id)');
        $this->addSql('CREATE INDEX IDX_A3CC27034793DA59 ON kantor (pembina_id)');
        $this->addSql('CREATE INDEX idx_kantor_nama_status ON kantor (id, nama, level, sk)');
        $this->addSql('CREATE INDEX idx_kantor_legacy ON kantor (id, legacy_kode, legacy_kode_kpp, legacy_kode_kanwil)');
        $this->addSql('CREATE INDEX idx_kantor_relation ON kantor (id, jenis_kantor_id, parent_id, level, pembina_id)');
        $this->addSql('CREATE INDEX idx_kantor_location ON kantor (id, latitude, longitude)');
        $this->addSql('COMMENT ON COLUMN kantor.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN kantor.jenis_kantor_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN kantor.parent_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN kantor.pembina_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN kantor.tanggal_aktif IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN kantor.tanggal_nonaktif IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE modul (id UUID NOT NULL, aplikasi_id UUID NOT NULL, nama VARCHAR(255) NOT NULL, system_name VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, create_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deskripsi TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9D57608852224EF8 ON modul (aplikasi_id)');
        $this->addSql('CREATE INDEX idx_modul_nama_status ON modul (nama, system_name, status)');
        $this->addSql('CREATE INDEX idx_modul_nama_aplikasi ON modul (aplikasi_id, nama, system_name)');
        $this->addSql('COMMENT ON COLUMN modul.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN modul.aplikasi_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN modul.create_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE pegawai (id UUID NOT NULL, user_id UUID NOT NULL, nama VARCHAR(255) NOT NULL, tanggal_lahir TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tempat_lahir VARCHAR(255) NOT NULL, pensiun BOOLEAN NOT NULL, npwp VARCHAR(255) DEFAULT NULL, nik VARCHAR(16) DEFAULT NULL, nip9 VARCHAR(9) DEFAULT NULL, nip18 VARCHAR(18) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_98835748A76ED395 ON pegawai (user_id)');
        $this->addSql('CREATE INDEX idx_pegawai_data ON pegawai (id, nama, pensiun, nik, nip9, nip18)');
        $this->addSql('CREATE INDEX idx_pegawai_legacy ON pegawai (id, nip9)');
        $this->addSql('CREATE INDEX idx_pegawai_relation ON pegawai (id, user_id)');
        $this->addSql('COMMENT ON COLUMN pegawai.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pegawai.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pegawai.tanggal_lahir IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE permission (id UUID NOT NULL, nama VARCHAR(255) NOT NULL, system_name VARCHAR(255) NOT NULL, deskripsi TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_permission_nama_status ON permission (id, nama, system_name)');
        $this->addSql('COMMENT ON COLUMN permission.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE permission_modul (permission_id UUID NOT NULL, modul_id UUID NOT NULL, PRIMARY KEY(permission_id, modul_id))');
        $this->addSql('CREATE INDEX IDX_4BD00DFBFED90CCA ON permission_modul (permission_id)');
        $this->addSql('CREATE INDEX IDX_4BD00DFB19952065 ON permission_modul (modul_id)');
        $this->addSql('COMMENT ON COLUMN permission_modul.permission_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN permission_modul.modul_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE role_permission (role_id UUID NOT NULL, permission_id UUID NOT NULL, PRIMARY KEY(role_id, permission_id))');
        $this->addSql('CREATE INDEX IDX_6F7DF886D60322AC ON role_permission (role_id)');
        $this->addSql('CREATE INDEX IDX_6F7DF886FED90CCA ON role_permission (permission_id)');
        $this->addSql('COMMENT ON COLUMN role_permission.role_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN role_permission.permission_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE refresh_tokens (id INT NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE role (id UUID NOT NULL, subs_of_role_id UUID DEFAULT NULL, nama VARCHAR(255) NOT NULL, system_name VARCHAR(255) NOT NULL, deskripsi TEXT DEFAULT NULL, level INT DEFAULT NULL, jenis INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_57698A6AB0FFC082 ON role (subs_of_role_id)');
        $this->addSql('CREATE INDEX idx_role_nama_status ON role (id, nama, system_name, jenis)');
        $this->addSql('CREATE INDEX idx_role_relation ON role (id, level, subs_of_role_id)');
        $this->addSql('COMMENT ON COLUMN role.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN role.subs_of_role_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN role.jenis IS \'Jenis Relasi Role: 1 => user, 2 => jabatan, 3 => unit, 4 => kantor, 5 => eselon,
             *          6 => jenis kantor, 7 => group, 8 => jabatan + unit, 9 => jabatan + kantor,
             *          10 => jabatan + unit + kantor\'');
        $this->addSql('CREATE TABLE role_user (role_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY(role_id, user_id))');
        $this->addSql('CREATE INDEX IDX_332CA4DDD60322AC ON role_user (role_id)');
        $this->addSql('CREATE INDEX IDX_332CA4DDA76ED395 ON role_user (user_id)');
        $this->addSql('COMMENT ON COLUMN role_user.role_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN role_user.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE role_jabatan (role_id UUID NOT NULL, jabatan_id UUID NOT NULL, PRIMARY KEY(role_id, jabatan_id))');
        $this->addSql('CREATE INDEX IDX_28B3D7AFD60322AC ON role_jabatan (role_id)');
        $this->addSql('CREATE INDEX IDX_28B3D7AFA7400487 ON role_jabatan (jabatan_id)');
        $this->addSql('COMMENT ON COLUMN role_jabatan.role_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN role_jabatan.jabatan_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE role_unit (role_id UUID NOT NULL, unit_id UUID NOT NULL, PRIMARY KEY(role_id, unit_id))');
        $this->addSql('CREATE INDEX IDX_62047EC7D60322AC ON role_unit (role_id)');
        $this->addSql('CREATE INDEX IDX_62047EC7F8BD700D ON role_unit (unit_id)');
        $this->addSql('COMMENT ON COLUMN role_unit.role_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN role_unit.unit_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE role_kantor (role_id UUID NOT NULL, kantor_id UUID NOT NULL, PRIMARY KEY(role_id, kantor_id))');
        $this->addSql('CREATE INDEX IDX_8EAC6B2D60322AC ON role_kantor (role_id)');
        $this->addSql('CREATE INDEX IDX_8EAC6B22C104734 ON role_kantor (kantor_id)');
        $this->addSql('COMMENT ON COLUMN role_kantor.role_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN role_kantor.kantor_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE role_eselon (role_id UUID NOT NULL, eselon_id UUID NOT NULL, PRIMARY KEY(role_id, eselon_id))');
        $this->addSql('CREATE INDEX IDX_F9F54AA6D60322AC ON role_eselon (role_id)');
        $this->addSql('CREATE INDEX IDX_F9F54AA62D0196DB ON role_eselon (eselon_id)');
        $this->addSql('COMMENT ON COLUMN role_eselon.role_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN role_eselon.eselon_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE role_jenis_kantor (role_id UUID NOT NULL, jenis_kantor_id UUID NOT NULL, PRIMARY KEY(role_id, jenis_kantor_id))');
        $this->addSql('CREATE INDEX IDX_D6C79E11D60322AC ON role_jenis_kantor (role_id)');
        $this->addSql('CREATE INDEX IDX_D6C79E115EB4E08C ON role_jenis_kantor (jenis_kantor_id)');
        $this->addSql('COMMENT ON COLUMN role_jenis_kantor.role_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN role_jenis_kantor.jenis_kantor_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE role_group (role_id UUID NOT NULL, group_id UUID NOT NULL, PRIMARY KEY(role_id, group_id))');
        $this->addSql('CREATE INDEX IDX_9A1CACEAD60322AC ON role_group (role_id)');
        $this->addSql('CREATE INDEX IDX_9A1CACEAFE54D947 ON role_group (group_id)');
        $this->addSql('COMMENT ON COLUMN role_group.role_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN role_group.group_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE tipe_jabatan (id UUID NOT NULL, nama VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_tipe_jabatan ON tipe_jabatan (id, nama)');
        $this->addSql('COMMENT ON COLUMN tipe_jabatan.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE unit (id UUID NOT NULL, jenis_kantor_id UUID NOT NULL, parent_id UUID DEFAULT NULL, eselon_id UUID NOT NULL, pembina_id UUID DEFAULT NULL, nama VARCHAR(255) NOT NULL, level INT NOT NULL, tanggal_aktif TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tanggal_nonaktif TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, legacy_kode VARCHAR(10) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DCBB0C535EB4E08C ON unit (jenis_kantor_id)');
        $this->addSql('CREATE INDEX IDX_DCBB0C53727ACA70 ON unit (parent_id)');
        $this->addSql('CREATE INDEX IDX_DCBB0C532D0196DB ON unit (eselon_id)');
        $this->addSql('CREATE INDEX IDX_DCBB0C534793DA59 ON unit (pembina_id)');
        $this->addSql('CREATE INDEX idx_unit_nama ON unit (id, nama, level)');
        $this->addSql('CREATE INDEX idx_unit_legacy ON unit (id, legacy_kode, pembina_id)');
        $this->addSql('CREATE INDEX idx_unit_relation ON unit (id, jenis_kantor_id, parent_id, eselon_id)');
        $this->addSql('COMMENT ON COLUMN unit.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN unit.jenis_kantor_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN unit.parent_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN unit.eselon_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN unit.pembina_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN unit.tanggal_aktif IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN unit.tanggal_nonaktif IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, username VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, locked BOOLEAN NOT NULL, two_factor_enabled BOOLEAN NOT NULL, last_change TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE INDEX idx_user_data ON "user" (id, username, password)');
        $this->addSql('CREATE INDEX idx_user_active ON "user" (id, active, locked)');
        $this->addSql('COMMENT ON COLUMN "user".id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE user_two_factor (id UUID NOT NULL, user_id UUID NOT NULL, backup_code JSON DEFAULT NULL, tfa_type INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AF21438EA76ED395 ON user_two_factor (user_id)');
        $this->addSql('CREATE INDEX idx_user_two_factor_data ON user_two_factor (id, tfa_type)');
        $this->addSql('CREATE INDEX idx_user_two_factor_relation ON user_two_factor (id, user_id)');
        $this->addSql('COMMENT ON COLUMN user_two_factor.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN user_two_factor.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE "group" ADD CONSTRAINT FK_6DC044C57E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_member ADD CONSTRAINT FK_A36222A82F68B530 FOREIGN KEY (group_id_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_member ADD CONSTRAINT FK_A36222A8A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE jabatan ADD CONSTRAINT FK_947E72542D0196DB FOREIGN KEY (eselon_id) REFERENCES eselon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE jabatan ADD CONSTRAINT FK_947E7254708D6535 FOREIGN KEY (group_jabatan_id) REFERENCES group_jabatan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE jabatan_unit ADD CONSTRAINT FK_C6797710A7400487 FOREIGN KEY (jabatan_id) REFERENCES jabatan (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE jabatan_unit ADD CONSTRAINT FK_C6797710F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE jabatan_pegawai ADD CONSTRAINT FK_53FE676A998300D9 FOREIGN KEY (pegawai_id) REFERENCES pegawai (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE jabatan_pegawai ADD CONSTRAINT FK_53FE676AA7400487 FOREIGN KEY (jabatan_id) REFERENCES jabatan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE jabatan_pegawai ADD CONSTRAINT FK_53FE676AC69A8E08 FOREIGN KEY (tipe_id) REFERENCES tipe_jabatan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE jabatan_pegawai ADD CONSTRAINT FK_53FE676A2C104734 FOREIGN KEY (kantor_id) REFERENCES kantor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE jabatan_pegawai ADD CONSTRAINT FK_53FE676AF8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE jabatan_pegawai ADD CONSTRAINT FK_53FE676A89E8E03D FOREIGN KEY (atribut_id) REFERENCES jabatan_atribut (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kantor ADD CONSTRAINT FK_A3CC27035EB4E08C FOREIGN KEY (jenis_kantor_id) REFERENCES jenis_kantor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kantor ADD CONSTRAINT FK_A3CC2703727ACA70 FOREIGN KEY (parent_id) REFERENCES kantor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kantor ADD CONSTRAINT FK_A3CC27034793DA59 FOREIGN KEY (pembina_id) REFERENCES kantor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE modul ADD CONSTRAINT FK_9D57608852224EF8 FOREIGN KEY (aplikasi_id) REFERENCES aplikasi (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pegawai ADD CONSTRAINT FK_98835748A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE permission_modul ADD CONSTRAINT FK_4BD00DFBFED90CCA FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE permission_modul ADD CONSTRAINT FK_4BD00DFB19952065 FOREIGN KEY (modul_id) REFERENCES modul (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_permission ADD CONSTRAINT FK_6F7DF886D60322AC FOREIGN KEY (role_id) REFERENCES permission (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_permission ADD CONSTRAINT FK_6F7DF886FED90CCA FOREIGN KEY (permission_id) REFERENCES role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role ADD CONSTRAINT FK_57698A6AB0FFC082 FOREIGN KEY (subs_of_role_id) REFERENCES role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_user ADD CONSTRAINT FK_332CA4DDD60322AC FOREIGN KEY (role_id) REFERENCES role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_user ADD CONSTRAINT FK_332CA4DDA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_jabatan ADD CONSTRAINT FK_28B3D7AFD60322AC FOREIGN KEY (role_id) REFERENCES role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_jabatan ADD CONSTRAINT FK_28B3D7AFA7400487 FOREIGN KEY (jabatan_id) REFERENCES jabatan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_unit ADD CONSTRAINT FK_62047EC7D60322AC FOREIGN KEY (role_id) REFERENCES role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_unit ADD CONSTRAINT FK_62047EC7F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_kantor ADD CONSTRAINT FK_8EAC6B2D60322AC FOREIGN KEY (role_id) REFERENCES role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_kantor ADD CONSTRAINT FK_8EAC6B22C104734 FOREIGN KEY (kantor_id) REFERENCES kantor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_eselon ADD CONSTRAINT FK_F9F54AA6D60322AC FOREIGN KEY (role_id) REFERENCES role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_eselon ADD CONSTRAINT FK_F9F54AA62D0196DB FOREIGN KEY (eselon_id) REFERENCES eselon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_jenis_kantor ADD CONSTRAINT FK_D6C79E11D60322AC FOREIGN KEY (role_id) REFERENCES role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_jenis_kantor ADD CONSTRAINT FK_D6C79E115EB4E08C FOREIGN KEY (jenis_kantor_id) REFERENCES jenis_kantor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_group ADD CONSTRAINT FK_9A1CACEAD60322AC FOREIGN KEY (role_id) REFERENCES role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_group ADD CONSTRAINT FK_9A1CACEAFE54D947 FOREIGN KEY (group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE unit ADD CONSTRAINT FK_DCBB0C535EB4E08C FOREIGN KEY (jenis_kantor_id) REFERENCES jenis_kantor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE unit ADD CONSTRAINT FK_DCBB0C53727ACA70 FOREIGN KEY (parent_id) REFERENCES unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE unit ADD CONSTRAINT FK_DCBB0C532D0196DB FOREIGN KEY (eselon_id) REFERENCES eselon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE unit ADD CONSTRAINT FK_DCBB0C534793DA59 FOREIGN KEY (pembina_id) REFERENCES unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_two_factor ADD CONSTRAINT FK_AF21438EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE modul DROP CONSTRAINT FK_9D57608852224EF8');
        $this->addSql('ALTER TABLE jabatan DROP CONSTRAINT FK_947E72542D0196DB');
        $this->addSql('ALTER TABLE role_eselon DROP CONSTRAINT FK_F9F54AA62D0196DB');
        $this->addSql('ALTER TABLE unit DROP CONSTRAINT FK_DCBB0C532D0196DB');
        $this->addSql('ALTER TABLE group_member DROP CONSTRAINT FK_A36222A82F68B530');
        $this->addSql('ALTER TABLE role_group DROP CONSTRAINT FK_9A1CACEAFE54D947');
        $this->addSql('ALTER TABLE jabatan DROP CONSTRAINT FK_947E7254708D6535');
        $this->addSql('ALTER TABLE jabatan_unit DROP CONSTRAINT FK_C6797710A7400487');
        $this->addSql('ALTER TABLE jabatan_pegawai DROP CONSTRAINT FK_53FE676AA7400487');
        $this->addSql('ALTER TABLE role_jabatan DROP CONSTRAINT FK_28B3D7AFA7400487');
        $this->addSql('ALTER TABLE jabatan_pegawai DROP CONSTRAINT FK_53FE676A89E8E03D');
        $this->addSql('ALTER TABLE kantor DROP CONSTRAINT FK_A3CC27035EB4E08C');
        $this->addSql('ALTER TABLE role_jenis_kantor DROP CONSTRAINT FK_D6C79E115EB4E08C');
        $this->addSql('ALTER TABLE unit DROP CONSTRAINT FK_DCBB0C535EB4E08C');
        $this->addSql('ALTER TABLE jabatan_pegawai DROP CONSTRAINT FK_53FE676A2C104734');
        $this->addSql('ALTER TABLE kantor DROP CONSTRAINT FK_A3CC2703727ACA70');
        $this->addSql('ALTER TABLE kantor DROP CONSTRAINT FK_A3CC27034793DA59');
        $this->addSql('ALTER TABLE role_kantor DROP CONSTRAINT FK_8EAC6B22C104734');
        $this->addSql('ALTER TABLE permission_modul DROP CONSTRAINT FK_4BD00DFB19952065');
        $this->addSql('ALTER TABLE jabatan_pegawai DROP CONSTRAINT FK_53FE676A998300D9');
        $this->addSql('ALTER TABLE permission_modul DROP CONSTRAINT FK_4BD00DFBFED90CCA');
        $this->addSql('ALTER TABLE role_permission DROP CONSTRAINT FK_6F7DF886D60322AC');
        $this->addSql('ALTER TABLE role_permission DROP CONSTRAINT FK_6F7DF886FED90CCA');
        $this->addSql('ALTER TABLE role DROP CONSTRAINT FK_57698A6AB0FFC082');
        $this->addSql('ALTER TABLE role_user DROP CONSTRAINT FK_332CA4DDD60322AC');
        $this->addSql('ALTER TABLE role_jabatan DROP CONSTRAINT FK_28B3D7AFD60322AC');
        $this->addSql('ALTER TABLE role_unit DROP CONSTRAINT FK_62047EC7D60322AC');
        $this->addSql('ALTER TABLE role_kantor DROP CONSTRAINT FK_8EAC6B2D60322AC');
        $this->addSql('ALTER TABLE role_eselon DROP CONSTRAINT FK_F9F54AA6D60322AC');
        $this->addSql('ALTER TABLE role_jenis_kantor DROP CONSTRAINT FK_D6C79E11D60322AC');
        $this->addSql('ALTER TABLE role_group DROP CONSTRAINT FK_9A1CACEAD60322AC');
        $this->addSql('ALTER TABLE jabatan_pegawai DROP CONSTRAINT FK_53FE676AC69A8E08');
        $this->addSql('ALTER TABLE jabatan_unit DROP CONSTRAINT FK_C6797710F8BD700D');
        $this->addSql('ALTER TABLE jabatan_pegawai DROP CONSTRAINT FK_53FE676AF8BD700D');
        $this->addSql('ALTER TABLE role_unit DROP CONSTRAINT FK_62047EC7F8BD700D');
        $this->addSql('ALTER TABLE unit DROP CONSTRAINT FK_DCBB0C53727ACA70');
        $this->addSql('ALTER TABLE unit DROP CONSTRAINT FK_DCBB0C534793DA59');
        $this->addSql('ALTER TABLE "group" DROP CONSTRAINT FK_6DC044C57E3C61F9');
        $this->addSql('ALTER TABLE group_member DROP CONSTRAINT FK_A36222A8A76ED395');
        $this->addSql('ALTER TABLE pegawai DROP CONSTRAINT FK_98835748A76ED395');
        $this->addSql('ALTER TABLE role_user DROP CONSTRAINT FK_332CA4DDA76ED395');
        $this->addSql('ALTER TABLE user_two_factor DROP CONSTRAINT FK_AF21438EA76ED395');
        $this->addSql('DROP SEQUENCE refresh_tokens_id_seq CASCADE');
        $this->addSql('DROP TABLE aplikasi');
        $this->addSql('DROP TABLE eselon');
        $this->addSql('DROP TABLE "group"');
        $this->addSql('DROP TABLE group_jabatan');
        $this->addSql('DROP TABLE group_member');
        $this->addSql('DROP TABLE jabatan');
        $this->addSql('DROP TABLE jabatan_unit');
        $this->addSql('DROP TABLE jabatan_atribut');
        $this->addSql('DROP TABLE jabatan_pegawai');
        $this->addSql('DROP TABLE jenis_kantor');
        $this->addSql('DROP TABLE kantor');
        $this->addSql('DROP TABLE modul');
        $this->addSql('DROP TABLE pegawai');
        $this->addSql('DROP TABLE permission');
        $this->addSql('DROP TABLE permission_modul');
        $this->addSql('DROP TABLE role_permission');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE role_user');
        $this->addSql('DROP TABLE role_jabatan');
        $this->addSql('DROP TABLE role_unit');
        $this->addSql('DROP TABLE role_kantor');
        $this->addSql('DROP TABLE role_eselon');
        $this->addSql('DROP TABLE role_jenis_kantor');
        $this->addSql('DROP TABLE role_group');
        $this->addSql('DROP TABLE tipe_jabatan');
        $this->addSql('DROP TABLE unit');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_two_factor');
    }
}
