controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_authentication:
    path: /api/authentication
    methods: ['POST']

api_token_invalidate:
    path: /api/token/invalidate
