controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_authentication:
    path: /api/authentication
    methods: ['POST']

api_token_invalidate:
    path: /api/token/invalidate
