#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_authentication:
  path: /api/authentication
  methods: ['POST']

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
