name: Releases

on: 
  push:
    tags:
    - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,foo/*.txt"
        token: ${{ secrets.GITHUB_TOKEN }}
